import type { ClientReportPayload } from "@/types/intelligence";

/**
 * Fallback static intelligence payload.
 * Mirrored from the real audited Shopee market run (2026-09-06).
 * Ensures zero-failure SSG build even when client_report.json has not yet been regenerated.
 */
export const FALLBACK_CLIENT_REPORT: ClientReportPayload = {
  generatedAt: "2026-09-06T01:10:30Z",
  edition: "Semana 36 • Setembro 2026",
  macro: {
    auditedListings: 497,
    weeklyRevenueBrl: 11500000,
    dailyUnitVelocity: 44520,
    medianPriceBrl: 29.94,
    priceP25Brl: 26.65,
    priceP75Brl: 38.99,
  },
  niches: [
    {
      id: "streetwear",
      name: "Streetwear & Urban",
      volume: 22,
      dailyVelocity: 4452,
      priceP25: 28.9,
      priceMedian: 36.9,
      priceP75: 49.9,
      tag: "Alta Margem",
      badge: "Alta Procura • Margem Segura",
      sharePercent: 14.5,
    },
    {
      id: "religioso",
      name: "Religioso & Cristão",
      volume: 52,
      dailyVelocity: 3593,
      priceP25: 21.9,
      priceMedian: 27.9,
      priceP75: 32.9,
      tag: "Guerra de Preço",
      badge: "Alto Volume • Margem Comprimida",
      sharePercent: 11.7,
    },
    {
      id: "anime",
      name: "Anime & Mangá",
      volume: 74,
      dailyVelocity: 3496,
      priceP25: 22.5,
      priceMedian: 28.9,
      priceP75: 34.9,
      tag: "Guerra de Preço",
      badge: "Saturação de Sellers (74+)",
      sharePercent: 11.4,
    },
    {
      id: "geek",
      name: "Geek & Super-Heróis",
      volume: 20,
      dailyVelocity: 2711,
      priceP25: 29.9,
      priceMedian: 35.0,
      priceP75: 42.9,
      tag: "Equilibrado",
      badge: "Comunidade Fiel",
      sharePercent: 8.8,
    },
    {
      id: "pets",
      name: "Pets & Animais",
      volume: 14,
      dailyVelocity: 2698,
      priceP25: 32.0,
      priceMedian: 39.9,
      priceP75: 47.5,
      tag: "Alta Margem",
      badge: "Presenteável • Baixa Sensibilidade",
      sharePercent: 8.8,
    },
    {
      id: "k-pop",
      name: "K-Pop & Coreia",
      volume: 31,
      dailyVelocity: 2190,
      priceP25: 31.9,
      priceMedian: 38.5,
      priceP75: 45.0,
      tag: "Alta Margem",
      badge: "Fandom Engajado • Alto Ticket",
      sharePercent: 7.1,
    },
    {
      id: "frutas-flores",
      name: "Frutas, Flores & Botânico",
      volume: 4,
      dailyVelocity: 1201,
      priceP25: 32.9,
      priceMedian: 42.0,
      priceP75: 54.9,
      tag: "Alta Margem",
      badge: "Alta Rentabilidade • Ticket Superior",
      sharePercent: 3.9,
    },
    {
      id: "musica",
      name: "Música & Bandas Vintage",
      volume: 18,
      dailyVelocity: 1077,
      priceP25: 27.5,
      priceMedian: 34.9,
      priceP75: 42.0,
      tag: "Equilibrado",
      badge: "Demanda Constante",
      sharePercent: 3.5,
    },
    {
      id: "nostalgia",
      name: "Nostalgia 90s/00s",
      volume: 7,
      dailyVelocity: 945,
      priceP25: 29.0,
      priceMedian: 36.0,
      priceP75: 44.0,
      tag: "Equilibrado",
      badge: "Público 30+ • Alto Poder Aquisitivo",
      sharePercent: 3.1,
    },
    {
      id: "esportes",
      name: "Esportes & Gym Culture",
      volume: 8,
      dailyVelocity: 820,
      priceP25: 28.0,
      priceMedian: 35.0,
      priceP75: 43.5,
      tag: "Equilibrado",
      badge: "Crescimento Rápido",
      sharePercent: 2.7,
    },
  ],
  fabricRadar: [
    {
      feature: "Algodão 30.1 Penteado",
      percentage: 54,
      trend: "up",
      description: "Padrão de ouro dos líderes. Menor devolução por encolhimento e melhor aderência a DTF.",
    },
    {
      feature: "Kits Promocionais (2 a 3 un)",
      percentage: 42,
      trend: "up",
      description: "Impulsionador do ticket médio e diluição do frete único no carrinho da Shopee.",
    },
    {
      feature: "Estampa Costas DTF",
      percentage: 38,
      trend: "up",
      description: "Tendência streetwear dominante: peito minimalista e grande painel gráfico nas costas.",
    },
    {
      feature: "Modelagem Oversized Boxy",
      percentage: 32,
      trend: "up",
      description: "Ombro caído e corte reto com maior margem unitária perceptível.",
    },
    {
      feature: "Gola Ribana 2x1 Canelada",
      percentage: 28,
      trend: "up",
      description: "Acabamento nobre de 3cm que impede a gola de esgarçar após lavagens repetidas.",
    },
  ],
  directives: {
    whatToPrint: [
      {
        niche: "Streetwear Boxy com Arte nas Costas",
        reason: "Preço mediano de R$ 36,90 com margens acima de 55%. Baixíssima guerra predatória de preços quando a estampa traz narrativa urbana.",
        recommendedThemes: ["Cyberpunk Vintage", "Frases Minimalistas", "Gráficos Heavy Acid Wash"],
        marginRating: "Alta",
      },
      {
        niche: "K-Pop & Aesthetic Minimalista",
        reason: "Compradores com alta tolerância a preço (R$ 38,50+). Fandoms fiéis que compram no impulso do lançamento de comebacks.",
        recommendedThemes: ["Linhas Finas / Line Art", "Tipografia Hangul", "Identidades Visuais de Álbuns"],
        marginRating: "Alta",
      },
      {
        niche: "Pets & Cães com Traço Ilustrado",
        reason: "Alta compra para presentes. Preço médio de R$ 39,90 e concorrência desatenta à qualidade de acabamento.",
        recommendedThemes: ["Raças Específicas (Golden, Dachshund)", "Gatos Humorísticos", "Ilustrações Vintage"],
        marginRating: "Alta",
      },
    ],
    whatToPause: [
      {
        niche: "Anime Shonen Genérico (Goku, Naruto)",
        reason: "Mais de 74 sellers disputando o topo da busca com preços de até R$ 22,50 em malhas sintéticas de baixo custo.",
        riskFactor: "Margem líquida abaixo de 18% com alto custo de ads.",
      },
      {
        niche: "Religioso Básico em Sublimação 100% Poliéster",
        reason: "Comercialização por grandes distribuidores atacadistas vendendo a preço de custo operacional (R$ 19,90).",
        riskFactor: "Guerra de preços destrutiva e incapacidade de competir no frete.",
      },
    ],
  },
  breakouts: [
    {
      id: "brk-01",
      title: "Camiseta Streetwear Oversized Vintage Acid Wash",
      imageUrl: "/images/prints/streetwear_01.webp",
      theme: "Streetwear",
      dailySales: 142,
      historicalSales: 4890,
      priceBrl: 44.9,
      shopeeItemCode: "BR-58256851422",
      specs: {
        cut: "Oversized Street Boxy (Gola 3cm Ribana)",
        fabric: "100% Algodão 30.1 Penteado (Gramatura 190g/m²)",
        printTechnique: "DTF Têxtil HD Frente (Peito 10cm) + Costas (Painel A3)",
        estimatedMargin: "58% a 65% (Markup 2.9x)",
        costEstimateBrl: 15.8,
        targetAudience: "Jovem 18-26 • Urbano / Hype",
      },
    },
    {
      id: "brk-02",
      title: "Camiseta K-Pop Blackpink Born Pink Typography",
      imageUrl: "/images/prints/kpop_01.webp",
      theme: "K-Pop",
      dailySales: 118,
      historicalSales: 3120,
      priceBrl: 42.0,
      shopeeItemCode: "BR-58213913937",
      specs: {
        cut: "Corte Regular Confortável Unissex",
        fabric: "100% Algodão 30.1 Penteado Toque Macio",
        printTechnique: "DTF Digital Neon com alta vivacidade",
        estimatedMargin: "62% a 68% (Markup 3.1x)",
        costEstimateBrl: 13.9,
        targetAudience: "Feminino / Jovem 14-24 • Fãs K-Pop",
      },
    },
    {
      id: "brk-03",
      title: "Camiseta Golden Retriever Ilustrado Minimalist Art",
      imageUrl: "/images/prints/pets_01.webp",
      theme: "Pets e Animais",
      dailySales: 96,
      historicalSales: 2240,
      priceBrl: 39.9,
      shopeeItemCode: "BR-58206621924",
      specs: {
        cut: "Casual Unissex com reforço de ombro a ombro",
        fabric: "Meia Malha 30.1 Penteada 165g/m²",
        printTechnique: "Silk Digital Kornit ou DTF Premium toque zero",
        estimatedMargin: "55% a 60% (Markup 2.6x)",
        costEstimateBrl: 14.5,
        targetAudience: "Tutores de Cães • Presenteável 22-45",
      },
    },
    {
      id: "brk-04",
      title: "Camiseta Botânica Flores Selvagens Aesthetic",
      imageUrl: "/images/prints/botanica_01.webp",
      theme: "Frutas e Flores",
      dailySales: 88,
      historicalSales: 1890,
      priceBrl: 46.5,
      shopeeItemCode: "BR-58213267011",
      specs: {
        cut: "Feminina Relaxed Fit / Gola Canelada",
        fabric: "100% Algodão Orgânico Pré-Encolhido",
        printTechnique: "DTF Têxtil Paleta Pastel",
        estimatedMargin: "60% a 66% (Markup 2.8x)",
        costEstimateBrl: 16.2,
        targetAudience: "Mulheres 20-35 • Estilo Cottagecore / Indie",
      },
    },
    {
      id: "brk-05",
      title: "Camiseta Rock Retrô 80s Band Tour Heavy Cotton",
      imageUrl: "/images/prints/rock_01.webp",
      theme: "Música e Bandas",
      dailySales: 84,
      historicalSales: 2780,
      priceBrl: 38.9,
      shopeeItemCode: "BR-58213889878",
      specs: {
        cut: "Corte Tradicional Reto Rockwear",
        fabric: "Algodão 30.1 Estonado / Lavanderia",
        printTechnique: "Silk Screen Policromia Base d'água",
        estimatedMargin: "52% a 57% (Markup 2.4x)",
        costEstimateBrl: 15.0,
        targetAudience: "Público 25-45 • Fãs de Classic Rock",
      },
    },
    {
      id: "brk-06",
      title: "Camiseta Cyberpunk Tokyo Neon Nights",
      imageUrl: "/images/prints/cyberpunk_01.webp",
      theme: "Streetwear",
      dailySales: 81,
      historicalSales: 1950,
      priceBrl: 43.9,
      shopeeItemCode: "BR-58214282696",
      specs: {
        cut: "Oversized Streetwear Unissex",
        fabric: "100% Algodão 26.1 Heavyweight (210g/m²)",
        printTechnique: "DTF Alta Resolução com Brilho Têxtil",
        estimatedMargin: "56% a 63% (Markup 2.7x)",
        costEstimateBrl: 16.5,
        targetAudience: "Gamers & Streetwear Fans 18-30",
      },
    },
    {
      id: "brk-07",
      title: "Camiseta Gato Preto Coffee & Books Minimalista",
      imageUrl: "/images/prints/pets_02.webp",
      theme: "Pets e Animais",
      dailySales: 76,
      historicalSales: 1640,
      priceBrl: 37.9,
      shopeeItemCode: "BR-58204156820",
      specs: {
        cut: "Unissex Tradicional Confort",
        fabric: "Algodão Penteado 30.1",
        printTechnique: "DTF Monocromático de Alto Contraste",
        estimatedMargin: "58% a 64% (Markup 2.7x)",
        costEstimateBrl: 13.5,
        targetAudience: "Amantes de Livros, Café e Gatos",
      },
    },
    {
      id: "brk-08",
      title: "Camiseta Nostalgia 90s Cassette Tape Retrô",
      imageUrl: "/images/prints/retro_01.webp",
      theme: "Nostalgia",
      dailySales: 69,
      historicalSales: 1420,
      priceBrl: 39.0,
      shopeeItemCode: "BR-58214477565",
      specs: {
        cut: "Regular Clássica com costura dupla",
        fabric: "100% Algodão Mescla ou Tinto",
        printTechnique: "DTF Efeito Desgastado / Vintage",
        estimatedMargin: "55% a 62% (Markup 2.6x)",
        costEstimateBrl: 14.0,
        targetAudience: "Millennials 30-45 • Fãs de nostalgia",
      },
    },
    {
      id: "brk-09",
      title: "Camiseta Calistenia / Gym Pump Cover Oversized",
      imageUrl: "/images/prints/gym_01.webp",
      theme: "Esportes",
      dailySales: 65,
      historicalSales: 1380,
      priceBrl: 44.0,
      shopeeItemCode: "BR-58250005797",
      specs: {
        cut: "Pump Cover Oversized Extra Largo",
        fabric: "100% Algodão 30.1 Penteado Encorpado",
        printTechnique: "DTF Costas Gigante com frases motivacionais",
        estimatedMargin: "57% a 64% (Markup 2.8x)",
        costEstimateBrl: 15.2,
        targetAudience: "Homens 18-32 • Praticantes de Musculação",
      },
    },
    {
      id: "brk-10",
      title: "Camiseta Aesthetic Lo-Fi Japanese Garden",
      imageUrl: "/images/prints/aesthetic_01.webp",
      theme: "Streetwear",
      dailySales: 62,
      historicalSales: 1290,
      priceBrl: 41.5,
      shopeeItemCode: "BR-23794612995",
      specs: {
        cut: "Boxy Moderno com gola redonda reforçada",
        fabric: "Malha Menegotti 30.1 Penteada",
        printTechnique: "DTF Toque Acetinado",
        estimatedMargin: "56% a 62% (Markup 2.7x)",
        costEstimateBrl: 14.8,
        targetAudience: "Público Jovem Geek / Lo-Fi 16-25",
      },
    },
    {
      id: "brk-11",
      title: "Camiseta Minimalista Linha Floral Traço Fino",
      imageUrl: "/images/prints/botanica_02.webp",
      theme: "Frutas e Flores",
      dailySales: 58,
      historicalSales: 1120,
      priceBrl: 38.5,
      shopeeItemCode: "BR-58264267203",
      specs: {
        cut: "Modelagem Baby Look Alongada ou Casual",
        fabric: "100% Algodão Toque Pluma",
        printTechnique: "Silk Plastisol 1 Cor / DTF Fino",
        estimatedMargin: "61% a 67% (Markup 3.0x)",
        costEstimateBrl: 12.8,
        targetAudience: "Mulheres 22-40 • Estilo Clean / Minimal",
      },
    },
    {
      id: "brk-12",
      title: "Camiseta K-Drama Korean Heart Typography",
      imageUrl: "/images/prints/kpop_02.webp",
      theme: "K-Pop",
      dailySales: 55,
      historicalSales: 980,
      priceBrl: 39.9,
      shopeeItemCode: "BR-58215823470",
      specs: {
        cut: "Corte Unissex Tradicional Confort",
        fabric: "100% Algodão 30.1 Macio",
        printTechnique: "DTF Peito + Mangas",
        estimatedMargin: "59% a 65% (Markup 2.8x)",
        costEstimateBrl: 13.6,
        targetAudience: "Fãs de Séries e Dramas Coreanos",
      },
    },
  ],
};
