"""Closed-Circuit Adaptive Seed Feedback Loop for Trend Scout Scraper.

Why: E-commerce demand evolves dynamically week-over-week. Instead of relying
solely on fixed static search seeds, this module feeds the highest-velocity themes
surfaced by previous trend reports directly back into the scraper's ingestion
pipeline as dynamic search keywords, while preserving permanent anchor seeds
for longitudinal continuity.
"""

from __future__ import annotations

import json
import logging
import re
import unicodedata
from pathlib import Path
from typing import Any

from core.config import get_settings

log = logging.getLogger(__name__)

# Curated dictionary mapping abstract cluster theme tags to high-intent Shopee search terms.
# Why: LLMs cluster items into natural language descriptions (e.g. 'rock e música'),
# but Brazilian Shopee shoppers search using compact, colloquial category hooks
# (e.g. 'camiseta rock vintage').
KNOWN_THEME_MAPPINGS: dict[str, str] = {
    "anime e geek": "camiseta anime geek",
    "religioso e cristao": "camiseta gospel crista",
    "religioso e cristão": "camiseta gospel crista",
    "country e sertanejo": "camiseta country agro",
    "rock e musica": "camiseta rock vintage",
    "rock e música": "camiseta rock vintage",
    "academia e fitness": "camiseta gym academia",
    "automotivo e motorsport": "camiseta automotiva moto",
    "geek e super-herois": "camiseta geek",
    "geek e super-heróis": "camiseta geek",
    "geek e super herois": "camiseta geek",
    "pets e animais": "camiseta pets",
    "memes e humor": "camiseta memes",
    "k-pop": "camiseta kpop",
    "kpop": "camiseta kpop",
    "k pop": "camiseta kpop",
    "vintage e retro": "camiseta vintage",
    "vintage e retrô": "camiseta vintage",
}

# Themes explicitly excluded from dynamic keyword exploration.
# Why: Non-printed items (plains/basics) and generic catch-alls dilute scraper quota
# with low-signal, non-target inventory that violates the core print-only business rule.
INVALID_THEMES: frozenset[str] = frozenset(
    {
        "nao-estampada",
        "nao estampada",
        "geral",
        "multitemas",
        "outros",
        "nenhum",
    }
)


def _strip_diacritics(text: str) -> str:
    """Normalize unicode characters to plain ASCII equivalents."""
    return "".join(
        c for c in unicodedata.normalize("NFKD", text) if not unicodedata.combining(c)
    )


def format_theme_search_keyword(theme: str) -> str:
    """Convert an analyzed product theme label into an optimal Shopee search term.

    Why: Raw theme names generated by LLM clustering often contain grammatical
    conjunctions, accents, or punctuation that depress match precision when sent
    to Shopee's search engine. Mapping known themes to curated search phrases and
    applying a uniform 'camiseta' prefix ensures the scraper queries highest-intent
    buyer search phrases.

    Args:
        theme: Raw theme name (e.g. 'Rock e Música', 'k-pop', 'Streetwear').

    Returns:
        High-intent search query string (e.g. 'camiseta rock vintage', 'camiseta kpop').
    """
    if not theme or not theme.strip():
        return "camiseta"

    raw = theme.strip().lower()
    if raw in KNOWN_THEME_MAPPINGS:
        return KNOWN_THEME_MAPPINGS[raw]

    # Check unaccented version against known mappings
    unaccented = _strip_diacritics(raw)
    if unaccented in KNOWN_THEME_MAPPINGS:
        return KNOWN_THEME_MAPPINGS[unaccented]

    # Strip punctuation and check again (e.g., 'rock e musica!' or 'k-pop!')
    cleaned_punct = re.sub(r"[^\w\s-]", "", unaccented).strip()
    if cleaned_punct in KNOWN_THEME_MAPPINGS:
        return KNOWN_THEME_MAPPINGS[cleaned_punct]

    cleaned_hyphen = re.sub(r"[^\w\s]", " ", unaccented)
    cleaned_hyphen = re.sub(r"\s+", " ", cleaned_hyphen).strip()
    if cleaned_hyphen in KNOWN_THEME_MAPPINGS:
        return KNOWN_THEME_MAPPINGS[cleaned_hyphen]

    # Cleaned theme without punctuation for general fallback
    cleaned_theme = re.sub(r"[^\w\s]", " ", raw)
    cleaned_theme = re.sub(r"\s+", " ", cleaned_theme).strip()

    if not cleaned_theme:
        return "camiseta"

    if cleaned_theme.startswith("camiseta"):
        return cleaned_theme
    return f"camiseta {cleaned_theme}"


def _is_invalid_theme(theme: str) -> bool:
    """Check whether a theme string is a generic or non-printed placeholder."""
    normalized = _strip_diacritics(theme.strip().lower())
    slug = re.sub(r"[^a-z0-9]+", "-", normalized).strip("-")
    spaced = re.sub(r"[^a-z0-9]+", " ", normalized).strip()
    return (
        normalized in INVALID_THEMES
        or slug in INVALID_THEMES
        or spaced in INVALID_THEMES
        or any(invalid in slug for invalid in ("nao-estampada", "nao estampada"))
    )


def _load_latest_report_payload(reports_dir: Path | None = None) -> dict[str, Any] | None:
    """Read the latest generated weekly report JSON payload from disk."""
    base_dir = reports_dir or (get_settings().data_dir / "reports")
    if not base_dir.exists():
        return None

    # Case 1: reports_dir points directly to a folder containing report.json
    direct_report = base_dir / "report.json"
    if direct_report.is_file():
        try:
            return json.loads(direct_report.read_text(encoding="utf-8"))
        except Exception as exc:
            log.warning("failed reading direct report %s: %s", direct_report, exc)
            return None

    # Case 2: reports_dir contains timestamped run folders (e.g. data/reports/20260907T120000Z/)
    if base_dir.is_dir():
        dirs = sorted(d for d in base_dir.iterdir() if d.is_dir() and (d / "report.json").is_file())
        if dirs:
            latest = dirs[-1]
            try:
                return json.loads((latest / "report.json").read_text(encoding="utf-8"))
            except Exception as exc:
                log.warning("failed reading latest report from %s: %s", latest, exc)
                return None

    return None


def get_adaptive_scrape_keywords(
    report_payload: dict[str, Any] | None = None,
    reports_dir: Path | None = None,
    max_total: int = 8,
) -> list[str]:
    """Resolve the active list of search queries blending anchor seeds and dynamic themes.

    Why: Fixed keyword configurations miss nascent consumer trends and overfit to
    static niches. By extracting high-velocity themes from the prior intelligence run,
    the scraper allocates dynamic slots to emerging winners while anchor seeds
    preserve baseline macro-tracking.

    Args:
        report_payload: Optional pre-loaded report payload dictionary.
        reports_dir: Optional custom path to reports directory for report discovery.
        max_total: Maximum number of search queries to return (defaults to 8).

    Returns:
        Ordered list of unique search terms composed of anchors plus dynamic exploration terms.
    """
    settings = get_settings()
    anchors = list(settings.scrape_anchor_keywords)

    target_dynamic_slots = max_total - len(anchors)
    if target_dynamic_slots <= 0:
        return anchors[:max_total]

    # Attempt to load report if not explicitly provided
    if report_payload is None:
        report_payload = _load_latest_report_payload(reports_dir)

    candidate_themes: list[str] = []
    if report_payload and isinstance(report_payload, dict):
        raw_vels = report_payload.get("theme_velocities")
        if raw_vels:
            if isinstance(raw_vels, dict):
                items = list(raw_vels.items())
            elif isinstance(raw_vels, list):
                items = []
                for entry in raw_vels:
                    if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                        items.append((str(entry[0]), entry[1]))
                    elif isinstance(entry, (list, tuple)) and len(entry) == 1:
                        items.append((str(entry[0]), 0.0))
                    elif isinstance(entry, str):
                        items.append((entry, 0.0))
            else:
                items = []
            items.sort(key=lambda kv: float(kv[1]) if kv[1] is not None else 0.0, reverse=True)
            candidate_themes = [kv[0] for kv in items]
        else:
            raw_counts = report_payload.get("theme_counts")
            if raw_counts:
                if isinstance(raw_counts, dict):
                    items = list(raw_counts.items())
                elif isinstance(raw_counts, list):
                    items = []
                    for entry in raw_counts:
                        if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                            items.append((str(entry[0]), entry[1]))
                        elif isinstance(entry, (list, tuple)) and len(entry) == 1:
                            items.append((str(entry[0]), 0))
                        elif isinstance(entry, str):
                            items.append((entry, 0))
                else:
                    items = []
                items.sort(key=lambda kv: float(kv[1]) if kv[1] is not None else 0.0, reverse=True)
                candidate_themes = [kv[0] for kv in items]

    anchor_normalized = {
        _strip_diacritics(a.strip().lower())
        for a in anchors
    }

    dynamic_keywords: list[str] = []
    dynamic_seen: set[str] = set()

    for theme in candidate_themes:
        if _is_invalid_theme(theme):
            continue

        keyword = format_theme_search_keyword(theme)
        kw_norm = _strip_diacritics(keyword.strip().lower())

        if kw_norm in anchor_normalized or kw_norm in dynamic_seen:
            continue

        dynamic_keywords.append(keyword)
        dynamic_seen.add(kw_norm)

        if len(dynamic_keywords) >= target_dynamic_slots:
            break

    # Cold start or sparse report backfill
    if len(dynamic_keywords) < target_dynamic_slots:
        for fallback in getattr(settings, "scrape_keywords", []):
            fb_clean = fallback.strip()
            fb_norm = _strip_diacritics(fb_clean.lower())
            if fb_norm not in anchor_normalized and fb_norm not in dynamic_seen:
                dynamic_keywords.append(fb_clean)
                dynamic_seen.add(fb_norm)
                if len(dynamic_keywords) >= target_dynamic_slots:
                    break

    return anchors + dynamic_keywords[:target_dynamic_slots]
